# ----------- CONFIGURABLE START -----------
title:            "오늘을 기억하다."
description:      "Charyum. Park"
url:              https://ryum91.github.io # Site url, without a slash at the end.
signoff:          "Ryum" # Your name

share:            true # Turn on twitter and facebook share buttons
disqus_id:        "ryum91"

github_url: 'https://github.com/ryum91'
facebook_url:
instagram_url:

facebook_appid:   544362209237824 # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-106652933-1 # Set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Home
    url:          /
    external:     false
  - name:         Dev
    url:          /dev
    external:     false
  - name:         Daily
    url:          /daily
    external:     false
  - name:         About
    url:          /about
    external:     false

# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
