# ----------- CONFIGURABLE START -----------
title:            "오늘의 기억"
description:      "Charyum. Park"
url:              http://memory.today # Site url, without a slash at the end.
signoff:          "Ryum" # Your name

share:            true # Turn on twitter and facebook share buttons
disqus_id:        "ryum91"
page_per_count:   10

github_url: 'https://github.com/ryum91'

facebook_appid:   544362209237824 # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-106652933-2 # Set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Dev
    url:          /dev/list
    external:     false
  - name:         Daily
    url:          /daily/list
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false

# ------------ CONFIGURABLE END ------------

permalink:        /:categories/post/:title
defaults:
  - values:
      layout: "default"
